### ISSUE TITLE
Obtain a new AdvancedDLSupport license grant

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#1]
Previously, Ultz had a license grant allowing static linking of ADL (the library we use for native interop) for iOS. This has since been invalidated and needs to be renewed for the rebrand of ElgarTK to Silk.NET.

# Details for the licensor
Library: Silk.NET
Licensor: Firwood Software
Licensee: Ultz Limited
Signatory: Jarl Gullberg

# Status
- [x] We're waiting for the licensor (@nihlus from @firwood-software) to grant a license.
- [x] We're waiting for the PDF version of the grant to be added to the Silk.NET-Docs repo
- [x] We're waiting for the plaintext version of the grant to be added to THIRD_PARTIED.md.
- [x] We're all set for mobile support.
