### ISSUE TITLE
Upstream spec to-do lists

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#106]
# OpenGL
- [x] Implement KhronosGroup/OpenGL-Registry#335
- [ ] Remove old groups (KhronosGroup/OpenGL-Registry#335)
    - note: needs working group consultation.
- [x] KhronosGroup/OpenGL-Registry#361
- [ ] KhronosGroup/OpenGL-Registry#360
- [x] KhronosGroup/OpenGL-Registry#359
- [x] KhronosGroup/OpenGL-Registry#358
- [x] KhronosGroup/OpenGL-Registry#357
- [x] KhronosGroup/OpenGL-Registry#356
- [x] KhronosGroup/OpenGL-Registry#355

# Vulkan
N/A

# OpenCL
N/A

# OpenVX
N/A

**Comment by Perksey** [comment]
Closing as the groups are fine now.
