### ISSUE TITLE
Setup a monthly continuous delivery routine

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#112]
# Jobs
- [ ] Create release/1.0 branch
- [ ] Create release/2.0 branch
- [ ] Set release/1.0 as default branch
- [ ] Setup monthly packs on master to main NuGet

**Comment by Pyrdacor** [comment]
This would be very nice. I use Silk.net in my project and work on a clean cross-platform build and want to be up-to-date with Silks bug fixes.

Would appreciate an implementation in the near future. :)

**Comment by Perksey** [comment]
We haven't discussed this yet but what we're likely going to do is release 1.0, and then have subsequent releases on the first friday of every month (lining up with the planned monthly working group meetings on the 2nd friday).

We'll also make `master` only for bugfixes and finished releases, `bleeding` where all the work on the next minor version happens (i.e. 1.1), and then `2.0` for Silk.NET 2.0.

**Comment by Pyrdacor** [comment]
As long as there will be nuget packages every month (or even better each week) which contain the latest features/bugfixes I am happy. :)

**Comment by Perksey** [comment]
While we haven't made this automatic (as I still want to manually specify the release notes and version number), we have laid out the branches similarly to what was discussed in the original issue (`master` is where 2.0 work will go when it commences, `latest` is where 1.X work will go) and setup a continuous delivery pipeline (so all we need to do is push a tag to release). Thus I deem this issue resolved.
