### ISSUE TITLE
2.0 RTM Blocking Issue Epic

### ISSUE THREAD

**Issue by Tyler-IN** [Ultz/Silk.NET#280]
## GLFW issues
- [x] #279 GLFW bindings on Linux need priority/location/name loader changes
- [ ] Ultz/NativePackages#2 GLFW v3.3.2 on OSX has problems with EGL/OES window creation, use v3.3.3 when it's released
- [x] Ultz/NativePackages#1 Targeting .Net framework does not copy glfw binary

**Comment by Perksey** [comment]
Reusing this issue as the 2.0 RTM Blocking Issue Epic

**Comment by Perksey** [comment]
All the issues we have the ability to address have been addressed. Closing...
