### ISSUE TITLE
Silk.NET is participating in Hacktoberfest!

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#318]
## Hacktoberfest
Hacktoberfest is open to everyone in the open source global community. Whether you’re a developer, student learning to code, event host, or company of any size, you can help drive growth of open source and make positive contributions to an ever-growing community. All backgrounds and skill levels are encouraged to complete the challenge.

We're pleased to announce that Silk.NET wants to help drive that growth of open source in releasing our own set of Hacktoberfest issues that anyone in the Silk.NET community should be able to tackle! One of our biggest barriers to contribution here at the Silk Team is that a lot of our issues require specialized knowledge in a specific area of both the industry and the library codebase itself, making it very hard to get into contributing.

This is why we've opened and/or picked out some relatively easy-going issues so that anyone can help out and contribute to Silk.NET! If you've been eyeing Silk.NET and want to get into it, or if you've been using it for a while and want to give something back to the Silk.NET community, now is your chance!

## Hacktoberfest Epic (these are some great issues open for you to tackle)
- [ ] #249 A high-level wrapper over our brand new 2.0 Assimp bindings! (Medium)
- [ ] #315 A proper demo application for our OpenGL bindings! (Large)
- [ ] #317 Some guides for various areas of Silk.NET! (Small-Medium)
- [ ] ~~#273 Adding launchSettings.json to our repo, so that we can better support some IDEs. (Very Small)~~
- [ ] #324 Adding an OpenAL example (Small)

## Free IDEs from JetBrains for Hacktoberfest participants
JetBrains has been a part of the global open-source community for years, from contributing to hundreds of open-source projects and releasing their own products as open-source, to supporting thousands of other contributors with complimentary licenses for their commercial tools.

This October, JetBrains are partnering with Hacktoberfest, a month-long celebration of open-source software, and they’d like to invite you to be a part of this exciting open-source journey. As a Platinum Sponsor of Hacktoberfest, JetBrains is pleased to provide you with access to the JetBrains Toolbox, which includes all our IDEs and .NET tools for all the various languages. For more information, head over to this link: https://www.jetbrains.com/lp/hacktoberfest-2020/

## Closing
That's all for now, if you have any questions feel free to post a question in the #team-talk channel in the Silk.NET Discord Server - where all of the development discussion for Silk.NET happens. Feel free to tell us how things go if you do end up tackling something here, too!

> **Dylan Perks**
> Chief Executive @ [Ultz](https://ultz.co.uk)
> Silk.NET Maintainer

**Comment by Perksey** [comment]
Archiving these issues for now, will reopen them next October.
