### ISSUE TITLE
Tracking issue for Silk.NET 2.0

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#48]
# Development
- [x] [Complete] DirectX and Windows bindings  **(!!!!!! MORE !!!!!!)** - @Perksey 
- [x] [Complete] Assimp bindings - @Perksey 
- [x] [Complete] Android support - @Perksey 
- [x] [Complete] iOS support **(!!!!! NEEDS ROBUSTNESS IMPROVEMENTS ASAP !!!!!)** - @Perksey 
- [x] [Complete] SDL support - @Perksey 
- [x] [Complete] Maths library - @HurricanKai 
- [x] [Complete] Bindings generator overhaul - @Perksey 
- [x] [Complete] OpenXR bindings - @Perksey
- [x] [Complete] Function pointer interop source generator - @HurricanKai 
- [x] [Complete] Overload overhaul (as discussed in 14/08/2020's meeting) - @Perksey

# Milestones
- [x] Preview 1 with Assimp and experimental OpenXR bindings (July 2020)
- [x] Preview 2 with SDL bindings/windowing support and new interop (~~Update Friday September~~ August 2020)
- [x] Preview 3 with mobile windowing support (~~Early October~~ Early November 2020)
- [x] Preview 4 with Maths, as well as DirectX bindings (Early December 2020)
- [x] Preview 5 release candidate (Late December 2020)
- [ ] Full release :tada: (New Year's Day 2021)

Dates are a loose estimate and are subject to change.
