### ISSUE TITLE
Tracking Issue for Silk.NET 1.0

### ISSUE THREAD

**Issue by Perksey** [Ultz/Silk.NET#5]
# Development
- [x] BuildTools - @Perksey 
- [x] OpenAL - @Nihlus
- [x] OpenGL - @Perksey 
- [x] OpenCL (after pre-release 3) - @Perksey 
- [x] GLFW - @devvoid 
- [x] Windowing (Desktop) - @devvoid
- [x] Input - @Perksey & @devvoid 
- [x] Vulkan (after pre-release 2) - @Perksey

# Workflow
- [x] Development Complete
- [x] Pre-release
- [x] AdvancedDLSupport grant obtained
- [x] Pre-release 2 (bugfix)
- [x] Add a metapackage containing the core spec of all subsystems.
- [x] Pre-release 3 with Vulkan support
- [x] Pre-release 4 with OpenCL support
- [x] Pre-release 5 (bugfix)
- [ ] 1.0 :tada:

# Miscellaneous Tasks
- [x] Setup Azure Pipelines
- [x] Setup a development NuGet feed

**Comment by Pyrdacor** [comment]
Congrats for 1.0 release :tada:

**Comment by Perksey** [comment]
Thanks!
